<a href="https://colab.research.google.com/github/shrishh9/AI_Lab_Assignments/blob/main/AI_Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1. Recursive DFS (Graph from CSV)
from google.colab import files
uploaded = files.upload()
import csv
def read_graph_from_csv(filename):
    graph = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            node, neighbors = row[0], row[1:]
            graph[node] = neighbors
    return graph

def dfs_recursive(graph, node, visited=None):
    if visited is None:
        visited = set()
    visited.add(node)
    print(node, end=' ')
    for neighbor in graph.get(node, []):
        if neighbor not in visited:
            dfs_recursive(graph, neighbor, visited)

graph = read_graph_from_csv('graph1.csv')
start_node = input("Enter start node: ")
dfs_recursive(graph, start_node)

Saving graph1.csv to graph1.csv
Enter start node: A
A B D  C E 

In [2]:
#1. Recursive Dfs. Read the undirected unweighted graph from a .csv file.
import csv
from collections import defaultdict

def read_graph_from_csv(filename):
    graph = defaultdict(list)
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header (source,destination)
        for source, destination in reader:
            graph[source].append(destination)
            graph[destination].append(source)  #coz it's undirected
    return graph

def dfs_recursive(graph, node, visited):
    if node not in visited:
        print(node, end=" ")
        visited.add(node)
        for neighbor in graph[node]:
            dfs_recursive(graph, neighbor, visited)

if __name__ == "__main__":
    filename = 'graph.csv'
    graph = read_graph_from_csv(filename)
    print("Graph adjacency list:")
    for node, neighbors in graph.items():
        print(f"{node}: {neighbors}")

    print("\nDFS traversal starting from 'A':")
    visited = set()
    dfs_recursive(graph, 'A', visited)

Graph adjacency list:
A: ['B', 'C']
B: ['A', 'D']
C: ['A', 'E']
D: ['B', 'E']
E: ['C', 'D']

DFS traversal starting from 'A':
A B D E C 

In [7]:
# 2. Non-Recursive DFS (Graph from user)
def dfs_non_recursive(graph, start):
    visited = set()
    stack = [start]
    while stack:
        node = stack.pop()
        if node not in visited:
            print(node, end=' ')
            visited.add(node)
            # reversed() to simulate stack behavior (LIFO)
            stack.extend(reversed(graph.get(node, [])))

# Read graph input
nodes = int(input("Enter number of nodes: "))
graph = {}
for _ in range(nodes):
    node = input("Enter node name: ")
    neighbors = input(f"Enter neighbors of {node} separated by space: ").split()
    graph[node] = neighbors

print("Graph structure:", graph)

start_node = input("Enter start node: ")
print("DFS Traversal:")
dfs_non_recursive(graph, start_node)

Enter number of nodes: 2
Enter node name: A
Enter neighbors of A separated by space: B C
Enter node name: C
Enter neighbors of C separated by space: D E
Graph structure: {'A': ['B', 'C'], 'C': ['D', 'E']}
Enter start node: A
DFS Traversal:
A B C D E 

In [8]:
# 3. BFS (Graph from user)
from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])
    while queue:
        node = queue.popleft()
        if node not in visited:
            print(node, end=' ')
            visited.add(node)
            queue.extend(graph.get(node, []))

# Example input same as above
graph = {}
n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Node: ")
    neighbors = input("Neighbors (space separated): ").split()
    graph[node] = neighbors
start = input("Start node: ")
bfs(graph, start)

Enter number of nodes: 2
Node: A
Neighbors (space separated): B C
Node: C
Neighbors (space separated): D E
Start node: A
A B C D E 

In [14]:
# 4. Best First Search (Directed, unweighted, user input)
import heapq

def best_first_search(graph, heuristic, start, goal):
    visited = set()
    # Priority queue stores (heuristic value, current node, path till now)
    queue = [(heuristic[start], start, [start])]

    while queue:
        current_heuristic, current_node, path = heapq.heappop(queue)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (Heuristic: {current_heuristic})")

            for neighbor in graph.get(current_node, []):
                if neighbor not in visited:
                    neighbor_heuristic = heuristic.get(neighbor, float('inf'))
                    heapq.heappush(queue, (neighbor_heuristic, neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ===== Input Section =====
graph = {}
heuristic = {}
n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Node: ")
    neighbors = input(f"Neighbors of {node} (space separated): ").split()
    graph[node] = neighbors
    heuristic[node] = int(input(f"Heuristic value of {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")
best_first_search(graph, heuristic, start, goal)



Enter number of nodes: 4
Node: A
Neighbors of A (space separated): B C
Heuristic value of A: 3
Node: B
Neighbors of B (space separated): D
Heuristic value of B: 2
Node: C
Neighbors of C (space separated): D
Heuristic value of C: 4
Node: D
Neighbors of D (space separated): 
Heuristic value of D: 0
Enter start node: A
Enter goal node: D
Visiting: A (Heuristic: 3)
Visiting: B (Heuristic: 2)
Path found: A -> B -> D


In [20]:
# Experiment 5: Best First Search (Undirected Weighted Graph, user input)

import heapq

def best_first_search(graph, heuristic, start, goal):
    visited = set()
    queue = [(heuristic[start], start, [start])]  # (heuristic, current_node, path_so_far)

    while queue:
        current_heuristic, current_node, path = heapq.heappop(queue)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (Heuristic: {current_heuristic})")

            for neighbor, weight in graph.get(current_node, []):
                if neighbor not in visited:
                    heapq.heappush(queue, (heuristic[neighbor], neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ===== User Input Section =====
graph = {}
heuristic = {}

n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Node: ")
    m = int(input(f"Enter number of neighbors for {node}: "))
    graph[node] = []
    for _ in range(m):
        neighbor, weight = input(f"Enter neighbor and weight (space separated): ").split()
        graph[node].append((neighbor, int(weight)))
    heuristic[node] = int(input(f"Heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

best_first_search(graph, heuristic, start, goal)

Enter number of nodes: 4
Node: A
Enter number of neighbors for A: 2
Enter neighbor and weight (space separated): B 3
Enter neighbor and weight (space separated): C 4
Heuristic value for A: 4
Node: B
Enter number of neighbors for B: 2
Enter neighbor and weight (space separated): A 3
Enter neighbor and weight (space separated): D 5
Heuristic value for B: 3
Node: C
Enter number of neighbors for C: 2
Enter neighbor and weight (space separated): A 3
Enter neighbor and weight (space separated): D 5
Heuristic value for C: 1
Node: D
Enter number of neighbors for D: 2
Enter neighbor and weight (space separated): B 3
Enter neighbor and weight (space separated): C 4
Heuristic value for D: 2
Enter start node: A
Enter goal node: D
Visiting: A (Heuristic: 4)
Visiting: C (Heuristic: 1)
Path found: A -> C -> D


In [21]:
# Experiment 6: Best First Search (Undirected Unweighted Graph, user input)

import heapq

def best_first_search(graph, heuristic, start, goal):
    visited = set()
    queue = [(heuristic[start], start, [start])]  # (heuristic, current_node, path_so_far)

    while queue:
        current_heuristic, current_node, path = heapq.heappop(queue)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (Heuristic: {current_heuristic})")

            for neighbor in graph.get(current_node, []):
                if neighbor not in visited:
                    heapq.heappush(queue, (heuristic[neighbor], neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ===== User Input Section =====
graph = {}
heuristic = {}

n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Node: ")
    neighbors = input(f"Enter neighbors of {node} (space separated): ").split()
    graph[node] = neighbors
    heuristic[node] = int(input(f"Heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

best_first_search(graph, heuristic, start, goal)


Enter number of nodes: 4
Node: A
Enter neighbors of A (space separated): B C
Heuristic value for A: 4
Node: B
Enter neighbors of B (space separated): A D
Heuristic value for B: 2
Node: C
Enter neighbors of C (space separated): A D
Heuristic value for C: 1
Node: D
Enter neighbors of D (space separated): B C
Heuristic value for D: 3
Enter start node: A
Enter goal node: D
Visiting: A (Heuristic: 4)
Visiting: C (Heuristic: 1)
Visiting: B (Heuristic: 2)
Path found: A -> B -> D


In [22]:
# Experiment 7: Best First Search (Directed Weighted Graph, user input)

import heapq

def best_first_search(graph, heuristic, start, goal):
    visited = set()
    queue = [(heuristic[start], start, [start])]  # (heuristic_value, node, path)

    while queue:
        current_heuristic, current_node, path = heapq.heappop(queue)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (Heuristic: {current_heuristic})")

            for neighbor, weight in graph.get(current_node, []):
                if neighbor not in visited:
                    heapq.heappush(queue, (heuristic[neighbor], neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ===== User Input Section =====
graph = {}
heuristic = {}

n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Enter node name: ")
    m = int(input(f"Enter number of neighbors for {node}: "))
    graph[node] = []
    for _ in range(m):
        neighbor, weight = input(f"Enter neighbor and weight (space separated): ").split()
        graph[node].append((neighbor, int(weight)))
    heuristic[node] = int(input(f"Heuristic value of {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

best_first_search(graph, heuristic, start, goal)

Enter number of nodes: 4
Enter node name: A
Enter number of neighbors for A: 2
Enter neighbor and weight (space separated): B 5
Enter neighbor and weight (space separated): C 3
Heuristic value of A: 4
Enter node name: B
Enter number of neighbors for B: 2
Enter neighbor and weight (space separated): A 3
Enter neighbor and weight (space separated): D 5
Heuristic value of B: 2
Enter node name: C
Enter number of neighbors for C: 2
Enter neighbor and weight (space separated): A 5
Enter neighbor and weight (space separated): D 3
Heuristic value of C: 1
Enter node name: D
Enter number of neighbors for D: 2
Enter neighbor and weight (space separated): B 5
Enter neighbor and weight (space separated): C 3
Heuristic value of D: 0
Enter start node: A
Enter goal node: D
Visiting: A (Heuristic: 4)
Visiting: C (Heuristic: 1)
Path found: A -> C -> D


In [24]:
# Experiment 8: A* Search (Directed Weighted Graph from CSV)

import csv
import heapq

def read_graph_from_csv(filename):
    graph = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if len(row) >= 3:
                src, dest, cost = row[0], row[1], int(row[2])
                if src not in graph:
                    graph[src] = []
                graph[src].append((dest, cost))
    return graph

def a_star_search(graph, heuristic, start, goal):
    open_list = [(heuristic[start], 0, start, [start])]  # (f_score, g_score, current_node, path_so_far)
    visited = set()

    while open_list:
        f_score, g_score, current_node, path = heapq.heappop(open_list)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            print(f"Total cost: {g_score}")
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (g: {g_score}, h: {heuristic[current_node]}, f: {f_score})")

            for neighbor, cost in graph.get(current_node, []):
                if neighbor not in visited:
                    g_new = g_score + cost
                    f_new = g_new + heuristic.get(neighbor, float('inf'))
                    heapq.heappush(open_list, (f_new, g_new, neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ==== Upload/Read your CSV file ====
# In Colab: Upload manually or mount Drive

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]  # Get uploaded file name
graph = read_graph_from_csv(filename)

# ==== Heuristic Input ====
heuristic = {}
nodes = list(graph.keys())  # Getting nodes from graph
for node in nodes:
    heuristic[node] = int(input(f"Enter heuristic value for {node}: "))
# Also, there could be nodes with no outgoing edge like 'D'
extra_nodes = set()
for dest_list in graph.values():
    for dest, _ in dest_list:
        if dest not in heuristic:
            extra_nodes.add(dest)
for node in extra_nodes:
    heuristic[node] = int(input(f"Enter heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

a_star_search(graph, heuristic, start, goal)

Saving graph8.csv to graph8.csv
Enter heuristic value for A: 1
Enter heuristic value for B: 3
Enter heuristic value for C: 2
Enter heuristic value for D: 5
Enter start node: A
Enter goal node: D
Visiting: A (g: 0, h: 1, f: 1)
Visiting: B (g: 1, h: 3, f: 4)
Visiting: C (g: 4, h: 2, f: 6)
Path found: A -> B -> D
Total cost: 3


In [25]:
# Experiment 9: A* Search (Directed Weighted Graph, user input)

import heapq

def a_star_search(graph, heuristic, start, goal):
    open_list = [(heuristic[start], 0, start, [start])]  # (f_score, g_score, current_node, path_so_far)
    visited = set()

    while open_list:
        f_score, g_score, current_node, path = heapq.heappop(open_list)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            print(f"Total cost: {g_score}")
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (g: {g_score}, h: {heuristic[current_node]}, f: {f_score})")

            for neighbor, cost in graph.get(current_node, []):
                if neighbor not in visited:
                    g_new = g_score + cost
                    f_new = g_new + heuristic.get(neighbor, float('inf'))
                    heapq.heappush(open_list, (f_new, g_new, neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ==== User Input Section ====
graph = {}
heuristic = {}

n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Enter node name: ")
    m = int(input(f"Enter number of neighbors for {node}: "))
    graph[node] = []
    for _ in range(m):
        neighbor, cost = input(f"Enter neighbor and cost (space separated): ").split()
        graph[node].append((neighbor, int(cost)))
    heuristic[node] = int(input(f"Heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

a_star_search(graph, heuristic, start, goal)

Enter number of nodes: 4
Enter node name: A
Enter number of neighbors for A: 2
Enter neighbor and cost (space separated): B 4
Enter neighbor and cost (space separated): C 3
Heuristic value for A: 5
Enter node name: B
Enter number of neighbors for B: 2
Enter neighbor and cost (space separated): A 2
Enter neighbor and cost (space separated): D 3
Heuristic value for B: 3
Enter node name: C
Enter number of neighbors for C: 2
Enter neighbor and cost (space separated): A 2
Enter neighbor and cost (space separated): D 3
Heuristic value for C: 2
Enter node name: D
Enter number of neighbors for D: B 4


ValueError: invalid literal for int() with base 10: 'B 4'

In [26]:
# Experiment 10: A* Search (Undirected Weighted Graph from CSV)

import csv
import heapq

def read_undirected_graph_from_csv(filename):
    graph = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if len(row) >= 3:
                src, dest, cost = row[0], row[1], int(row[2])
                if src not in graph:
                    graph[src] = []
                if dest not in graph:
                    graph[dest] = []
                graph[src].append((dest, cost))
                graph[dest].append((src, cost))  # Important! Add reverse edge
    return graph

def a_star_search(graph, heuristic, start, goal):
    open_list = [(heuristic[start], 0, start, [start])]  # (f_score, g_score, current_node, path_so_far)
    visited = set()

    while open_list:
        f_score, g_score, current_node, path = heapq.heappop(open_list)

        if current_node == goal:
            print("Path found:", ' -> '.join(path))
            print(f"Total cost: {g_score}")
            return

        if current_node not in visited:
            visited.add(current_node)
            print(f"Visiting: {current_node} (g: {g_score}, h: {heuristic[current_node]}, f: {f_score})")

            for neighbor, cost in graph.get(current_node, []):
                if neighbor not in visited:
                    g_new = g_score + cost
                    f_new = g_new + heuristic.get(neighbor, float('inf'))
                    heapq.heappush(open_list, (f_new, g_new, neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ==== Upload/Read your CSV file ====
# In Colab: Upload manually or mount Drive

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]  # Get uploaded file name
graph = read_undirected_graph_from_csv(filename)

# ==== Heuristic Input ====
heuristic = {}
all_nodes = list(graph.keys())

for node in all_nodes:
    heuristic[node] = int(input(f"Enter heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

a_star_search(graph, heuristic, start, goal)


Saving graph10.csv to graph10.csv
Enter heuristic value for A: 3
Enter heuristic value for B: 1
Enter heuristic value for C: 4
Enter heuristic value for D: 2
Enter heuristic value for E: 3
Enter start node: A
Enter goal node: E
Visiting: A (g: 0, h: 3, f: 3)
Visiting: B (g: 1, h: 1, f: 2)
Visiting: D (g: 3, h: 2, f: 5)
Path found: A -> B -> D -> E
Total cost: 4


In [27]:
# Experiment 11: A* Search (Undirected Weighted Graph, user input)

import heapq

def a_star_search(graph, heuristic, start, goal):
    open_list = [(heuristic[start], 0, start, [start])]  # (f_score, g_score, node, path_so_far)
    visited = set()

    while open_list:
        f_score, g_score, node, path = heapq.heappop(open_list)

        if node == goal:
            print("Path found:", ' -> '.join(path))
            print(f"Total cost: {g_score}")
            return

        if node not in visited:
            visited.add(node)
            print(f"Visiting: {node} (g: {g_score}, h: {heuristic[node]}, f: {f_score})")

            for neighbor, cost in graph.get(node, []):
                if neighbor not in visited:
                    g_new = g_score + cost
                    f_new = g_new + heuristic.get(neighbor, float('inf'))
                    heapq.heappush(open_list, (f_new, g_new, neighbor, path + [neighbor]))

    print("Goal not reachable.")

# ==== User Input Section ====
graph = {}
heuristic = {}

n = int(input("Enter number of nodes: "))
for _ in range(n):
    node = input("Enter node name: ")
    m = int(input(f"Enter number of neighbors for {node}: "))
    graph[node] = []
    for _ in range(m):
        neighbor, cost = input(f"Enter neighbor and cost (space separated): ").split()
        graph[node].append((neighbor, int(cost)))
        # Because undirected, add reverse edge too
        if neighbor not in graph:
            graph[neighbor] = []
        graph[neighbor].append((node, int(cost)))
    heuristic[node] = int(input(f"Heuristic value for {node}: "))

# Check for nodes with no outgoing edges
for node in graph.keys():
    if node not in heuristic:
        heuristic[node] = int(input(f"Heuristic value for {node}: "))

start = input("Enter start node: ")
goal = input("Enter goal node: ")

a_star_search(graph, heuristic, start, goal)

Enter number of nodes: 4
Enter node name: A
Enter number of neighbors for A: 2
Enter neighbor and cost (space separated): B 4
Enter neighbor and cost (space separated): C 2
Heuristic value for A: 4
Enter node name: B
Enter number of neighbors for B: 2
Enter neighbor and cost (space separated): A 3
Enter neighbor and cost (space separated): D 5
Heuristic value for B: 3
Enter node name: C
Enter number of neighbors for C: 2
Enter neighbor and cost (space separated): A 3
Enter neighbor and cost (space separated): D 5
Heuristic value for C: 1
Enter node name: D
Enter number of neighbors for D: 2
Enter neighbor and cost (space separated): B 4
Enter neighbor and cost (space separated): C 2
Heuristic value for D: 1
Enter start node: A
Enter goal node: D
Visiting: A (g: 0, h: 4, f: 4)
Visiting: C (g: 2, h: 1, f: 3)
Path found: A -> C -> D
Total cost: 4


In [28]:
# Experiment 12: Fuzzy Set Operations (3 fuzzy sets)

def fuzzy_union(A, B):
    return {x: max(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_intersection(A, B):
    return {x: min(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_complement(A):
    return {x: 1 - v for x, v in A.items()}

# Input 3 fuzzy sets
A = {'x1': 0.2, 'x2': 0.5, 'x3': 0.7}
B = {'x1': 0.4, 'x2': 0.6, 'x4': 0.9}
C = {'x2': 0.1, 'x3': 0.8, 'x4': 0.3}

print("Union of A and B:", fuzzy_union(A, B))
print("Intersection of B and C:", fuzzy_intersection(B, C))
print("Complement of A:", fuzzy_complement(A))

Union of A and B: {'x2': 0.6, 'x1': 0.4, 'x4': 0.9, 'x3': 0.7}
Intersection of B and C: {'x2': 0.1, 'x1': 0, 'x4': 0.3, 'x3': 0}
Complement of A: {'x1': 0.8, 'x2': 0.5, 'x3': 0.30000000000000004}


In [29]:
# Experiment 13: De Morgan's Law (Complement of Union)
def fuzzy_union(A, B):
    return {x: max(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_complement(A):
    return {x: 1 - v for x, v in A.items()}
# Input 2 fuzzy sets
A = {'x1': 0.3, 'x2': 0.7}
B = {'x1': 0.5, 'x2': 0.4}
# Complement of Union
union_AB = fuzzy_union(A, B)
complement_union = fuzzy_complement(union_AB)

print("Complement of (A U B):", complement_union)

Complement of (A U B): {'x2': 0.30000000000000004, 'x1': 0.5}


In [30]:
# Experiment 14: De Morgan's Law (Complement of Intersection)

def fuzzy_intersection(A, B):
    return {x: min(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_complement(A):
    return {x: 1 - v for x, v in A.items()}

# Input 2 fuzzy sets
A = {'x1': 0.2, 'x2': 0.8}
B = {'x1': 0.6, 'x2': 0.5}

# Complement of Intersection
intersection_AB = fuzzy_intersection(A, B)
complement_intersection = fuzzy_complement(intersection_AB)

print("Complement of (A ∩ B):", complement_intersection)

Complement of (A ∩ B): {'x2': 0.5, 'x1': 0.8}


In [31]:
# Experiment 15: Nim Game using Min-Max Algorithm

def nim_minmax(piles, turn):
    # Base case: if all piles are empty
    if all(pile == 0 for pile in piles):
        if turn == 'computer':
            return False
        else:
            return True

    if turn == 'computer':
        for i in range(len(piles)):
            for remove in range(1, piles[i]+1):
                new_piles = piles.copy()
                new_piles[i] -= remove
                if nim_minmax(new_piles, 'user'):
                    return True
        return False
    else:
        for i in range(len(piles)):
            for remove in range(1, piles[i]+1):
                new_piles = piles.copy()
                new_piles[i] -= remove
                if not nim_minmax(new_piles, 'computer'):
                    return False
        return True

def computer_move(piles):
    for i in range(len(piles)):
        for remove in range(1, piles[i]+1):
            new_piles = piles.copy()
            new_piles[i] -= remove
            if nim_minmax(new_piles, 'user'):
                print(f"Computer removes {remove} from pile {i+1}")
                piles[i] -= remove
                return
    # Otherwise random move
    for i in range(len(piles)):
        if piles[i] > 0:
            print(f"Computer removes 1 from pile {i+1}")
            piles[i] -= 1
            return

def nim_game():
    piles = list(map(int, input("Enter initial piles separated by space: ").split()))
    turn = 'user'

    while any(pile > 0 for pile in piles):
        print("Current Piles:", piles)
        if turn == 'user':
            pile_index = int(input("Choose pile (1,2,3...): ")) - 1
            remove = int(input(f"How many to remove from pile {pile_index+1}: "))
            if 0 <= pile_index < len(piles) and 1 <= remove <= piles[pile_index]:
                piles[pile_index] -= remove
                turn = 'computer'
            else:
                print("Invalid move, try again!")
        else:
            computer_move(piles)
            turn = 'user'

    if turn == 'computer':
        print("Congratulations! You win!")
    else:
        print("Computer wins!")

# Start game
nim_game()

Enter initial piles separated by space: 3 4 5
Current Piles: [3, 4, 5]
Choose pile (1,2,3...): 3
How many to remove from pile 3: 2
Current Piles: [3, 4, 3]
Computer removes 4 from pile 2
Current Piles: [3, 0, 3]
Choose pile (1,2,3...): 1
How many to remove from pile 1: 3
Current Piles: [0, 0, 3]
Computer removes 3 from pile 3
Computer wins!


In [ ]:
# Corrected Experiment 16: Nim Game using Min-Max where computer loses or draws

def is_terminal(piles):
    return all(pile == 0 for pile in piles)

def minimax(piles, turn):
    if is_terminal(piles):
        if turn == 'computer':
            return 1  # User wins
        else:
            return -1  # Computer wins (should be avoided)

    if turn == 'user':
        max_eval = -float('inf')
        for i in range(len(piles)):
            for remove in range(1, piles[i]+1):
                new_piles = piles.copy()
                new_piles[i] -= remove
                eval = minimax(new_piles, 'computer')
                max_eval = max(max_eval, eval)
        return max_eval
    else:  # Computer's turn
        min_eval = float('inf')
        for i in range(len(piles)):
            for remove in range(1, piles[i]+1):
                new_piles = piles.copy()
                new_piles[i] -= remove
                eval = minimax(new_piles, 'user')
                min_eval = min(min_eval, eval)
        return min_eval

def computer_move(piles):
    best_move = None
    best_value = float('inf')  # Computer tries to maximize user's winning chances

    for i in range(len(piles)):
        for remove in range(1, piles[i]+1):
            new_piles = piles.copy()
            new_piles[i] -= remove
            move_value = minimax(new_piles, 'user')
            if move_value < best_value:
                best_value = move_value
                best_move = (i, remove)

    if best_move:
        pile_index, remove = best_move
        print(f"Computer removes {remove} from pile {pile_index+1}")
        piles[pile_index] -= remove

def nim_game_computer_loses():
    piles = list(map(int, input("Enter initial piles separated by space: ").split()))
    turn = 'user'

    while any(pile > 0 for pile in piles):
        print("Current Piles:", piles)
        if turn == 'user':
            pile_index = int(input("Choose pile (1,2,3...): ")) - 1
            remove = int(input(f"How many to remove from pile {pile_index+1}: "))
            if 0 <= pile_index < len(piles) and 1 <= remove <= piles[pile_index]:
                piles[pile_index] -= remove
                turn = 'computer'
            else:
                print("Invalid move, try again!")
        else:
            computer_move(piles)
            turn = 'user'

    if turn == 'computer':
        print("Congratulations! You win!")
    else:
        print("Computer wins!")

# Start corrected Nim Game
nim_game_computer_loses()


Enter initial piles separated by space:  4 4 4
Current Piles: [4, 4, 4]
Choose pile (1,2,3...): 1
How many to remove from pile 1: 3
Current Piles: [1, 4, 4]
Computer removes 1 from pile 1
Current Piles: [0, 4, 4]
Choose pile (1,2,3...): 2
How many to remove from pile 2: 3
Current Piles: [0, 1, 4]
Computer removes 3 from pile 3
Current Piles: [0, 1, 1]


In [33]:
# Experiment 17: Simple MLP with random weights (N inputs, 2 hidden layers, 1 output)

import numpy as np

def simple_mlp(N):
    # Random weight initialization
    input_layer = np.random.randint(0, 2, N)
    hidden1 = np.random.rand(N, 5)  # First hidden layer with 5 neurons
    hidden2 = np.random.rand(5, 3)  # Second hidden layer with 3 neurons
    output_layer = np.random.rand(3, 1)  # Output neuron

    bias1 = np.random.rand(5)
    bias2 = np.random.rand(3)
    bias_out = np.random.rand(1)

    print("Input Layer:", input_layer)
    print("Hidden Layer 1 weights:\n", hidden1)
    print("Hidden Layer 2 weights:\n", hidden2)
    print("Output Layer weights:\n", output_layer)
    print("Biases Hidden1:", bias1)
    print("Biases Hidden2:", bias2)
    print("Bias Output:", bias_out)

simple_mlp(int(input("Enter number of binary inputs N: ")))

Enter number of binary inputs N: 3
Input Layer: [1 1 0]
Hidden Layer 1 weights:
 [[0.94696851 0.68559631 0.86970326 0.4832514  0.02885503]
 [0.22963571 0.6348479  0.11073711 0.40857404 0.22549877]
 [0.97983546 0.12003016 0.82072416 0.97896666 0.15726143]]
Hidden Layer 2 weights:
 [[0.04636575 0.84209833 0.61541309]
 [0.2263729  0.70494918 0.96199766]
 [0.07899888 0.85077464 0.9084174 ]
 [0.428653   0.45518912 0.24289316]
 [0.91991972 0.68006316 0.33641188]]
Output Layer weights:
 [[0.64532766]
 [0.00549591]
 [0.45764784]]
Biases Hidden1: [0.73771708 0.56785346 0.76824851 0.69489747 0.08574849]
Biases Hidden2: [0.40054346 0.87255031 0.54410209]
Bias Output: [0.32089853]


In [34]:
# Experiment 18: Simple MLP with 4 inputs, 1 hidden layer, 2 outputs (random weights)

import numpy as np

def simple_mlp_fixed():
    input_layer = np.random.randint(0, 2, 4)
    hidden = np.random.rand(4, 5)  # 5 hidden neurons
    output_layer = np.random.rand(5, 2)  # 2 outputs

    bias_hidden = np.random.rand(5)
    bias_output = np.random.rand(2)

    print("Input Layer:", input_layer)
    print("Hidden Layer weights:\n", hidden)
    print("Output Layer weights:\n", output_layer)
    print("Biases Hidden Layer:", bias_hidden)
    print("Biases Output Layer:", bias_output)

simple_mlp_fixed()

Input Layer: [1 1 0 1]
Hidden Layer weights:
 [[0.39930871 0.91984412 0.72724043 0.20065199 0.52410487]
 [0.71845313 0.37326347 0.42196972 0.50822064 0.10914484]
 [0.64022168 0.06393987 0.51917821 0.48068097 0.15574661]
 [0.30762379 0.37418368 0.48877102 0.92364237 0.94555923]]
Output Layer weights:
 [[0.9379568  0.48142899]
 [0.93003441 0.921737  ]
 [0.95319487 0.53692192]
 [0.41887427 0.5544784 ]
 [0.68338345 0.80211778]]
Biases Hidden Layer: [0.29674547 0.54482207 0.64854036 0.71148252 0.6623252 ]
Biases Output Layer: [0.20756182 0.36222308]


In [35]:
# Experiment 19: MLP with Backpropagation and Sigmoid

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mlp_sigmoid(X, y, epochs=10000, learning_rate=0.5):
    np.random.seed(1)
    hidden_weights = np.random.rand(X.shape[1], 4)
    output_weights = np.random.rand(4, 1)

    hidden_bias = np.random.rand(1, 4)
    output_bias = np.random.rand(1, 1)

    for _ in range(epochs):
        hidden_layer_input = np.dot(X, hidden_weights) + hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, output_weights) + output_bias
        predicted_output = sigmoid(output_layer_input)

        error = y - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)

        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
        output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
        hidden_weights += X.T.dot(d_hidden_layer) * learning_rate
        hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    print("Final hidden weights:", hidden_weights)
    print("Final output weights:", output_weights)
    print("Final hidden biases:", hidden_bias)
    print("Final output biases:", output_bias)

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

mlp_sigmoid(X, y)

Final hidden weights: [[ 3.16040446  2.09595821  2.48105925  6.74771973]
 [ 3.71642527 -1.08434045  3.15093112  6.44603707]]
Final output weights: [[-6.96144027]
 [-2.89650915]
 [-5.66207991]
 [10.76730372]]
Final hidden biases: [[-5.37009401  1.13754151 -4.44623543 -2.91262015]]
Final output biases: [[-2.3178838]]


In [36]:
# Experiment 20: MLP with Backpropagation and ReLU

import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def mlp_relu(X, y, epochs=10000, learning_rate=0.01):
    np.random.seed(2)
    hidden_weights = np.random.rand(X.shape[1], 4)
    output_weights = np.random.rand(4, 1)

    hidden_bias = np.random.rand(1, 4)
    output_bias = np.random.rand(1, 1)

    for _ in range(epochs):
        hidden_layer_input = np.dot(X, hidden_weights) + hidden_bias
        hidden_layer_output = relu(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, output_weights) + output_bias
        predicted_output = relu(output_layer_input)

        error = y - predicted_output
        d_predicted_output = error * relu_derivative(predicted_output)

        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * relu_derivative(hidden_layer_output)

        output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
        output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
        hidden_weights += X.T.dot(d_hidden_layer) * learning_rate
        hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    print("Final hidden weights:", hidden_weights)
    print("Final output weights:", output_weights)
    print("Final hidden biases:", hidden_bias)
    print("Final output biases:", output_bias)

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

mlp_relu(X, y)

Final hidden weights: [[ 0.40456434 -0.02631716  0.22623762  0.39695446]
 [ 0.36115211  0.30834531  0.1381827   0.53649435]]
Final output weights: [[-0.08021039]
 [ 0.09015251]
 [ 0.27385746]
 [-0.0683555 ]]
Final hidden biases: [[0.05773956 0.45684572 0.02572638 0.66790618]]
Final output biases: [[0.50205522]]


In [37]:
# Experiment 21: MLP with Backpropagation and Tanh Activation

import numpy as np

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.square(x)

def mlp_tanh(X, y, epochs=10000, learning_rate=0.01):
    np.random.seed(3)
    hidden_weights = np.random.rand(X.shape[1], 4)
    output_weights = np.random.rand(4, 1)

    hidden_bias = np.random.rand(1, 4)
    output_bias = np.random.rand(1, 1)

    for _ in range(epochs):
        hidden_layer_input = np.dot(X, hidden_weights) + hidden_bias
        hidden_layer_output = tanh(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, output_weights) + output_bias
        predicted_output = tanh(output_layer_input)

        error = y - predicted_output
        d_predicted_output = error * tanh_derivative(predicted_output)

        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * tanh_derivative(hidden_layer_output)

        output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
        output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
        hidden_weights += X.T.dot(d_hidden_layer) * learning_rate
        hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    print("Final hidden weights:", hidden_weights)
    print("Final output weights:", output_weights)
    print("Final hidden biases:", hidden_bias)
    print("Final output biases:", output_bias)

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

mlp_tanh(X, y)

Final hidden weights: [[0.4654151  2.19335943 1.01569505 0.57152559]
 [0.87460147 2.15612849 0.99990659 0.3810431 ]]
Final output weights: [[-0.38675746]
 [ 2.17554998]
 [-2.23688389]
 [-0.38871873]]
Final hidden biases: [[ 0.64292158 -0.64032751 -1.46787821  0.73162679]]
Final output biases: [[-0.31797082]]


In [3]:
#22. Write a program to read a text file with at least 30 sentences and 200 words and perform the following tasks in the given sequence.
#a. Text cleaning by removing punctuation/special characters, numbers and extra white spaces. Use regular expression for the same.
#b. Convert text to lowercase
#c. Tokenization
#d. Remove stop words
#e. Correct misspelled words
import re
import nltk
from nltk.corpus import stopwords
from textblob import TextBlob

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Download the punkt_tab resource

# Step 1: Read the file
with open('sample_text.txt', 'r') as file:
    text = file.read()

# Step 2: Text Cleaning - Remove punctuation, special characters, numbers, extra spaces
text = re.sub(r'[^a-zA-Z\s]', '', text)  # Keep only letters and spaces
text = re.sub(r'\s+', ' ', text).strip()  # Replace multiple spaces with single space

# Step 3: Convert to lowercase
text = text.lower()

# Step 4: Tokenization
tokens = nltk.word_tokenize(text)

# Step 5: Remove stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]

# Step 6: Correct misspelled words
corrected_tokens = []
for word in filtered_tokens:
    blob = TextBlob(word)
    corrected_word = str(blob.correct())
    corrected_tokens.append(corrected_word)

# Final output
print("Cleaned and Processed Tokens:\n")
print(corrected_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Cleaned and Processed Tokens:

['upon', 'time', 'village', 'far', 'away', 'lived', 'curious', 'young', 'boy', 'every', 'morning', 'would', 'wander', 'woods', 'looking', 'adventure', 'birds', 'chirped', 'melodious', 'air', 'smelled', 'fresh', 'sweet', 'one', 'day', 'found', 'old', 'dusty', 'map', 'buried', 'beneath', 'tree', 'map', 'promised', 'treasures', 'beyond', 'imagination', 'eagerly', 'shared', 'discovery', 'friends', 'together', 'decided', 'follow', 'map', 'journey', 'easy', 'rivers', 'crossed', 'hills', 'climbed', 'sometimes', 'got', 'lost', 'retract', 'steps', 'one', 'afternoon', 'started', 'raining', 'heavily', 'soaked', 'tired', 'sought', 'shelter', 'large', 'oak', 'tree', 'old', 'man', 'approached', 'warned', 'dangers', 'lay', 'ahead', 'however', 'spirit', 'unbreakable', 'thanked', 'continued', 'dawn', 'stumbled', 'upon', 'hidden', 'cave', 'inside', 'found', 'ancient', 'artifacts', 'glittering', 'jewels', 'joy', 'knew', 'bounds', 'realized', 'real', 'treasure', 'adventure',

In [4]:
#23. Write a program to read a text file with at least 30 sentences and 200 words and perform the following tasks in the given sequence.
#a. Text cleaning by removing punctuation/special characters, numbers and extra white spaces. Use regular expression for the same.
#b. Convert text to lowercase
#c. Stemming and Lemmatization
#d. Create a list of 3 consecutive words after lemmatization
import re
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')  # WordNet corpus for lemmatizer
nltk.download('stopwords')

# Step 1: Read the file
with open('sample_text.txt', 'r') as file:
    text = file.read()

# Step 2: Text Cleaning
text = re.sub(r'[^a-zA-Z\s]', '', text)  # Keep only letters and spaces
text = re.sub(r'\s+', ' ', text).strip()  # Remove extra white spaces

# Step 3: Convert to lowercase
text = text.lower()

# Step 4: Tokenization
tokens = nltk.word_tokenize(text)

# Step 5: Stemming
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(word) for word in tokens]

# Step 6: Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in stemmed_tokens]

# Step 7: Create list of 3 consecutive words (triplets)
triplets = []
for i in range(len(lemmatized_tokens) - 2):
    triplet = (lemmatized_tokens[i], lemmatized_tokens[i+1], lemmatized_tokens[i+2])
    triplets.append(triplet)

# Final Output
print("Sample of triplets:\n")
for t in triplets[:10]:  # Print first 10 triplets as a sample
    print(t)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Sample of triplets:

('onc', 'upon', 'a')
('upon', 'a', 'time')
('a', 'time', 'in')
('time', 'in', 'a')
('in', 'a', 'villag')
('a', 'villag', 'far')
('villag', 'far', 'away')
('far', 'away', 'live')
('away', 'live', 'a')
('live', 'a', 'curiou')


In [5]:
#24.Write a program to read a 3 text files on any technical concept with at least 20 sentences and 150 words. Implement one-hot encoding.
import re
from sklearn.preprocessing import MultiLabelBinarizer

# Step 1: Read the files
file_paths = ['machine_learning.txt', 'cloud_computing.txt', 'blockchain.txt']
documents = []

for path in file_paths:
    with open(path, 'r') as file:
        text = file.read()
        text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove punctuations/special chars
        text = text.lower()
        documents.append(text)

# Step 2: Tokenize each document into words
tokenized_docs = [doc.split() for doc in documents]

# Step 3: Create vocabulary (all unique words)
vocabulary = sorted(set(word for doc in tokenized_docs for word in doc))

print("Vocabulary size:", len(vocabulary))

# Step 4: One-hot encode using MultiLabelBinarizer
mlb = MultiLabelBinarizer(classes=vocabulary)
one_hot_encoded = mlb.fit_transform(tokenized_docs)

# Step 5: Display one-hot encoded vectors
for idx, vec in enumerate(one_hot_encoded):
    print(f"\nOne-Hot Encoding for Document {idx+1}:")
    print(vec)


Vocabulary size: 284

One-Hot Encoding for Document 1:
[1 0 1 1 1 0 0 1 0 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1
 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 0
 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0
 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 0 0
 0 1 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 1 0 0]

One-Hot Encoding for Document 2:
[1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0
 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0
 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0
 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 0 0

In [6]:
#25. Write a program to read a 3 text files on a movie review with at least 20 sentences and 150 words. Implement bag of words.
from sklearn.feature_extraction.text import CountVectorizer
import re

# Step 1: Read the files
file_paths = ['machine_learning.txt', 'blockchain.txt', 'cloud_computing.txt']
documents = []

for path in file_paths:
    with open(path, 'r') as file:
        text = file.read()
        # Basic cleaning
        text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove punctuation and numbers
        text = text.lower()
        documents.append(text)

# Step 2: Create Bag of Words Model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Step 3: Display
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nBag of Words Matrix (Each row = Document, Each column = Word frequency):")
print(X.toarray())

Vocabulary:
['access' 'accuracy' 'across' 'address' 'advantages' 'agreements'
 'algorithms' 'allows' 'amazon' 'among' 'analyze' 'and' 'application'
 'applications' 'architectures' 'are' 'artificial' 'as' 'assess'
 'automatic' 'availability' 'azure' 'based' 'becomes' 'behind' 'being'
 'beyond' 'bitcoin' 'block' 'blockchain' 'blockchains' 'blocks' 'built'
 'businesses' 'can' 'cases' 'categorized' 'chain' 'challenges' 'cleaning'
 'cloud' 'clouds' 'composed' 'compute' 'computers' 'computing' 'concerns'
 'consensus' 'consumption' 'containing' 'continues' 'contracts' 'corda'
 'core' 'cost' 'costs' 'creating' 'crossvalidation' 'crucial'
 'cryptocurrencies' 'cryptographic' 'dapps' 'data' 'databases' 'deals'
 'decentralized' 'decision' 'deep' 'demand' 'detection' 'developers'
 'developing' 'different' 'disaster' 'distributed' 'down' 'each' 'ec'
 'economical' 'edge' 'efficiency' 'eliminates' 'emerging' 'enable'
 'enables' 'encryption' 'energy' 'engineering' 'ensures' 'enterprisegrade'
 'ethereum

In [7]:
#26. Write a program to read a 3 text files a tourist place with at least 20 sentences and 150 words. Implement TF-IDF.
from sklearn.feature_extraction.text import TfidfVectorizer
import re

# Step 1: Read the files
file_paths = ['machine_learning.txt', 'blockchain.txt', 'cloud_computing.txt']
documents = []

for path in file_paths:
    with open(path, 'r') as file:
        text = file.read()
        # Basic cleaning
        text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove punctuation and numbers
        text = text.lower()
        documents.append(text)

# Step 2: Create TF-IDF Model
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Step 3: Display
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix (Each row = Document, Each column = Word importance):")
print(X.toarray())


Vocabulary:
['access' 'accuracy' 'across' 'address' 'advantages' 'agreements'
 'algorithms' 'allows' 'amazon' 'among' 'analyze' 'and' 'application'
 'applications' 'architectures' 'are' 'artificial' 'as' 'assess'
 'automatic' 'availability' 'azure' 'based' 'becomes' 'behind' 'being'
 'beyond' 'bitcoin' 'block' 'blockchain' 'blockchains' 'blocks' 'built'
 'businesses' 'can' 'cases' 'categorized' 'chain' 'challenges' 'cleaning'
 'cloud' 'clouds' 'composed' 'compute' 'computers' 'computing' 'concerns'
 'consensus' 'consumption' 'containing' 'continues' 'contracts' 'corda'
 'core' 'cost' 'costs' 'creating' 'crossvalidation' 'crucial'
 'cryptocurrencies' 'cryptographic' 'dapps' 'data' 'databases' 'deals'
 'decentralized' 'decision' 'deep' 'demand' 'detection' 'developers'
 'developing' 'different' 'disaster' 'distributed' 'down' 'each' 'ec'
 'economical' 'edge' 'efficiency' 'eliminates' 'emerging' 'enable'
 'enables' 'encryption' 'energy' 'engineering' 'ensures' 'enterprisegrade'
 'ethereum